apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  labels:
    app: acmefit
    service: catalog-api
spec:
  ports:
    - name: http-catalog-api
      protocol: TCP
      port: 8082
  selector:
    app: acmefit
    service: catalog-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels:
    app: acmefit
    service: catalog-api
    version: v1
spec:
  selector:
    matchLabels:
      app: acmefit
      service: catalog-api
      version: v1
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: catalog-api
        version: v1
    spec:
      volumes:
      - name: acmefit-catalog-data
        emptyDir: {}
      containers:
      - image: sadakunihiro/crud-backend
        name: catalog-api
        env:
        - name: CATALOG_DB_HOST
          value: 'catalog-mongo'
        - name: CATALOG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-mongo-pass
              key: password
        - name: CATALOG_DB_PORT
          value: '27017'
        - name: CATALOG_DB_USERNAME
          value: 'mongoadmin'
        - name: PORT
          value: '8082'
        ports:
        - containerPort: 8082
          name: http-catalog
