apiVersion: v1
kind: Service
metadata:
  name: catalog-frontend
  labels:
    app: acmefit
    service: catalog-frontend
spec:
  ports:
    - name: catalog-frontend
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: acmefit
    service: catalog-frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-frontend
  labels:
    app: acmefit
    service: catalog-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: acmefit
      service: catalog-frontend
      version: v1
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: catalog-frontend
        version: v1
    spec:
      containers:
      - image: sadakunihiro/crud-frontend
        name: catalog-frontend
        env:
        - name: VUE_APP_API_URL
          value: 'http://catalog-api:8082'
        - name: PORT
          value: '3000'
        ports:
        - containerPort: 3000
          name: http-catalog
